"""Add review model

Revision ID: 9eddd107d507
Revises: e0a63cadc7d9
Create Date: 2023-09-04 22:57:03.000963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eddd107d507'
down_revision = 'e0a63cadc7d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
